<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DotNetTargetFrameworks)</TargetFrameworks>
		<Description>Entity Framework Core components for the Lucile Framework. For detailed Documentation visit http://www.github.com/codeworxOS/Lucile</Description>
		<AssemblyTitle>Lucile Framework Entity Framework Core Library</AssemblyTitle>
		<Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(EfVersion)' == '10'">
		<TargetFrameworks>net10.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '8'">
		<TargetFrameworks>net8</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '9'">
		<TargetFrameworks>net8</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug EF100'">
		<TargetFrameworks>net10.0</TargetFrameworks>
		<EfVersion>10</EfVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug EF80'">
		<TargetFrameworks>net8</TargetFrameworks>
		<EfVersion>8</EfVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug EF90'">
		<TargetFrameworks>net8</TargetFrameworks>
		<EfVersion>9</EfVersion>
	</PropertyGroup>


	<PropertyGroup Condition="'$(EfVersion)' == '' And '$(TargetFramework)' == 'net10.0'">
		<EfVersion>10</EfVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '' And '$(TargetFramework)' == 'net8'">
		<EfVersion>8</EfVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '' And '$(TargetFramework)' == 'net9'">
		<EfVersion>9</EfVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(EfVersion)' == '10'">
		<DefineConstants>EF10</DefineConstants>
		<EnablePackageValidation>false</EnablePackageValidation>
		<PackageValidationBaselineVersion>2.1000.0</PackageValidationBaselineVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '8'">
		<DefineConstants>EF8</DefineConstants>
		<PackageValidationBaselineVersion>2.8000.0</PackageValidationBaselineVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(EfVersion)' == '9'">
		<DefineConstants>EF9</DefineConstants>
		<PackageValidationBaselineVersion>2.9000.0</PackageValidationBaselineVersion>
	</PropertyGroup>



	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Lucile.Core\Lucile.Core.csproj" />
	</ItemGroup>
</Project>