<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>ServiceModel Extensions for the Lucile Framework. For detailed Documentation visit http://www.github.com/codeworxOS/Lucile</Description>
    <AssemblyTitle>Lucile Framework Service Model Library</AssemblyTitle>
    <Authors>codeworx GmbH</Authors>
    <TargetFrameworks>$(FullAndCoreTargetFrameworks)</TargetFrameworks>
    <Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" />
    <PackageReference Include="System.ServiceModel.NetTcp" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lucile.Primitives\Lucile.Primitives.csproj" />
  </ItemGroup>
</Project>