# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-latest

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'lucile_signkey.snk'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'lucile_signkey.snk'
    TargetFolder: './private'
- task: PowerShell@2
  inputs:
    filePath: './tools/build.ps1'
    workingDirectory: './tools'
  displayName: 'Run the build script'
- task: CopyFiles@2
  inputs:
    SourceFolder: './dist/nuget'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'