<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(NetStandardTargetFrameworks)</TargetFrameworks>
		<Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Reflection.Emit.ILGeneration" />
		<PackageReference Include="System.Reflection.Emit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Lucile.Primitives\Lucile.Primitives.csproj" />
	</ItemGroup>
</Project>