<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetStandardTargetFrameworks)</TargetFramework>
    <Configurations>Debug;Release;Debug EF60;Debug EF80;Debug EF90;Debug EF100</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lucile.Dynamic\Lucile.Dynamic.csproj" />
  </ItemGroup>
</Project>