<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<Configurations>Debug;Release;Debug EF100;Debug EF70;Debug EF80;Debug EF90</Configurations>
		<EnablePackageValidation>false</EnablePackageValidation>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="protobuf-net" />
		<PackageReference Include="System.Reflection.TypeExtensions" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Lucile.EntityFramework\Lucile.EntityFramework.csproj" />
		<ProjectReference Include="..\Lucile.Test.Model\Lucile.Test.Model.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.Configuration" />
	</ItemGroup>
	<ItemGroup>
		<Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
	</ItemGroup>
</Project>