<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DotNetTargetFrameworks)</TargetFrameworks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
	  <EnablePackageValidation>false</EnablePackageValidation>

  </PropertyGroup>
  <ItemGroup>
    <None Remove="Serialization\previous-model.json" />
    <None Remove="Serialization\previous-model.proto" />
    <None Remove="Serialization\previous-model.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lucile.Core.Test.Module1\Lucile.Core.Test.Module1.csproj" />
    <ProjectReference Include="..\..\src\Lucile.Core\Lucile.Core.csproj" />
    <ProjectReference Include="..\Lucile.Signed.Test.Model\Lucile.Signed.Test.Model.csproj" />
    <ProjectReference Include="..\Lucile.Test.Model\Lucile.Test.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Remove="StyleCop.Analyzers" />
    <EmbeddedResource Include="Serialization\previous-model.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Serialization\previous-model.proto">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Serialization\previous-model.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk">
    </PackageReference>
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="xunit">
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>