<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetStandardTargetFrameworks)</TargetFramework>
		<AssemblyName>Lucile.Test.Model</AssemblyName>
		<PackageId>Lucile.Test.Model</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<Configurations>Debug;Release;Debug EF100;Debug EF70;Debug EF80;Debug EF90</Configurations>
		<EnablePackageValidation>false</EnablePackageValidation>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.ComponentModel.Annotations" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Lucile.Primitives\Lucile.Primitives.csproj" />
	</ItemGroup>

</Project>
