<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DotNetTargetFrameworks)</TargetFrameworks>
		<AssemblyName>Lucile.EntityFrameworkCore.Test</AssemblyName>
		<PackageId>Lucile.EntityFrameworkCore.Test</PackageId>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<Configurations>Debug;Release;Debug EF31;Debug EF50;Debug EF100;Debug EF80;Debug EF90</Configurations>
		<EnablePackageValidation>false</EnablePackageValidation>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)'=='Debug EF100'">
		<TargetFrameworks>net10</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug EF80'">
		<TargetFrameworks>net8</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug EF90'">
		<TargetFrameworks>net8</TargetFrameworks>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\src\Lucile.EntityFrameworkCore\Lucile.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\Lucile.Test.Model\Lucile.Test.Model.csproj" />
	</ItemGroup>

	<ItemGroup>

		<PackageReference Remove="StyleCop.Analyzers" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="protobuf-net" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
	</ItemGroup>

	<ItemGroup>
		<Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
	</ItemGroup>
</Project>