<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
		<EnablePackageValidation>false</EnablePackageValidation>
	</PropertyGroup>
	<ItemGroup>

		<PackageReference Remove="StyleCop.Analyzers" />
		<PackageReference Include="Microsoft.NET.Test.Sdk">
		</PackageReference>
		<PackageReference Include="xunit">
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Lucile.Dynamic.DependencyInjection\Lucile.Dynamic.DependencyInjection.csproj" />
		<ProjectReference Include="..\..\src\Lucile.ServiceModel.DependencyInjection\Lucile.ServiceModel.DependencyInjection.csproj" />
		<ProjectReference Include="..\..\src\Lucile.ServiceModel\Lucile.ServiceModel.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.ServiceModel.Web" />
	</ItemGroup>
</Project>