
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucile.ViewModel
{
    public partial class ViewModelBase : Lucile.NotificationObject, Lucile.ViewModel.IActivationAware, Lucile.ViewModel.INavigationAware{
		
	partial void OnIsActiveChanging(bool oldValue, bool newValue, ref bool handled);
	partial void OnIsActiveChanged();
	private bool valIsActive;
	
		public bool IsActive{
			 get
			{
				return valIsActive;
			}
			private set
			{
				if (valIsActive != value)
 
				{
					bool handled = false;
					OnIsActiveChanging(valIsActive, value,ref handled);
					handled = handled || RaisePropertyChanging("IsActive",valIsActive, value);
					if (!handled){
						valIsActive = value;
						OnIsActiveChanged();
						RaisePropertyChanged("IsActive");
					}
				}
			}
		}
	}
}
