<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DotNetTargetFrameworks)</TargetFrameworks>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<IsPackable>false</IsPackable>
		<Configurations>Debug;Release;Debug EF100;Debug EF80;Debug EF90</Configurations>
		<EnablePackageValidation>false</EnablePackageValidation>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Remove="StyleCop.Analyzers" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="System.ComponentModel.Annotations" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Lucile.Core\Lucile.Core.csproj" />
		<ProjectReference Include="..\..\src\Lucile.Dynamic.DependencyInjection\Lucile.Dynamic.DependencyInjection.csproj" />
		<ProjectReference Include="..\..\src\Lucile.Dynamic\Lucile.Dynamic.csproj" />
		<ProjectReference Include="..\..\src\Lucile.Primitives\Lucile.Primitives.csproj" />
		<ProjectReference Include="..\..\src\Lucile.ServiceModel\Lucile.ServiceModel.csproj" />
	</ItemGroup>
</Project>